name: 'verify references issue exists'
description: 'A GitHub action that verifies a pull request contains a reference to an issue.'
branding:
    icon: check-square
    color: green
inputs:
  comment:
    enabled: false
    message:
      description: The text to use as the PR comment for when for pull requests with no linked issues.
  filename:
      description: The name of the file to use as the comment template for pull requests with no linked issues.

runs:
  using: 'node16'
  main: 'src/index.js'

